version: "3.1"
services:
  nginx:
    image: nginx:latest
    ports:
      - "83:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public_html:/var/www
      - ./logs:/var/log/nginx
  php7.3:
    build: .
    volumes:
      - ./public_html:/var/www
  mysql:
    image: mariadb:latest
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/docker.cnf:/etc/mysql/conf.d/docker.cnf
    command:
      'mysqld --innodb-flush-method=fsync'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8082:80"
